name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install deps
        run: opam install ci
      - name: Lint
        run: opam exec -- run lint
